# Generated by Django 5.2.4 on 2025-07-07 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptask', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='delivery',
            name='grade',
            field=models.CharField(blank=True, choices=[('A', 'Excelente'), ('B', 'Bueno'), ('C', 'Regular'), ('D', 'Necesita mejorar'), ('F', 'Insuficiente')], max_length=1, null=True),
        ),
    ]
