# Generated by Django 5.2.4 on 2025-07-15 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptask', '0002_user_password_reset_expires_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dni',
            field=models.CharField(help_text='Cédula de 10 dígitos', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Estudiante'), ('teacher', 'Docente'), ('admin', 'Administrador'), ('observer', 'Observador')], default='student', max_length=20),
        ),
        migrations.AlterModelTable(
            name='user',
            table='apptask_user',
        ),
    ]
