# Generated by Django 5.2.4 on 2025-07-07 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptask', '0002_alter_delivery_options_delivery_grade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'ordering': ['-date', '-delivery_time']},
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_time',
            field=models.TimeField(default='12:00', help_text='Hora de entrega'),
        ),
        migrations.AddField(
            model_name='task',
            name='delivery_time',
            field=models.TimeField(default='23:59', help_text='Hora límite de entrega'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='grade',
            field=models.FloatField(blank=True, help_text='Calificación numérica (0.0 - 10.0)', null=True),
        ),
    ]
