# Generated by Django 5.2.4 on 2025-07-07 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptask', '0003_alter_delivery_options_delivery_delivery_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='grade',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Calificación numérica (0.00 - 10.00)', max_digits=4, null=True),
        ),
    ]
