# Generated by Django 5.2.4 on 2025-07-21 00:02

import apptask.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptask', '0003_alter_user_dni_alter_user_role_alter_user_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='attachment',
            field=models.FileField(blank=True, help_text='Archivo adjunto para la tarea (PDF, DOC, DOCX, TXT, máximo 10MB)', null=True, upload_to=apptask.models.task_file_upload_path, verbose_name='Archivo adjunto'),
        ),
    ]
