# Generated by Django 5.2.4 on 2025-07-21 00:21

import apptask.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptask', '0004_task_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='attachment',
            field=models.FileField(blank=True, help_text='Archivo de entrega (PDF, DOC, DOCX, TXT, ZIP, máximo 10MB)', null=True, upload_to=apptask.models.delivery_file_upload_path, verbose_name='Archivo de entrega'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='file_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
