# Generated by Django 5.2.4 on 2025-07-21 00:39

import apptask.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptask', '0005_delivery_attachment_alter_delivery_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='corrected_attachment',
            field=models.FileField(blank=True, help_text='Archivo corregido del profesor (PDF, DOC, DOCX, TXT, ZIP, máximo 10MB)', null=True, upload_to=apptask.models.corrected_file_upload_path, verbose_name='Archivo corregido'),
        ),
    ]
