# Generated by Django 5.2.4 on 2025-07-21 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptask', '0007_add_notification_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='unit',
            field=models.CharField(default='3', max_length=100),
        ),
    ]
