# Generated by Django 5.2.4 on 2025-07-21 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptask', '0008_schoolclass_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolclass',
            name='unit',
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='units_count',
            field=models.PositiveIntegerField(default=3, help_text='Cantidad de unidades en la clase'),
        ),
    ]
