# Generated by Django 5.2.4 on 2025-07-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptask', '0010_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='unit',
            field=models.PositiveIntegerField(default=3, help_text='Cantidad de unidades en la clase'),
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
