# Generated by Django 5.2.4 on 2025-07-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptask', '0011_task_unit_delete_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_timeout_minutes', models.PositiveIntegerField(default=30, help_text='Tiempo de inactividad en minutos antes de cerrar la sesión')),
                ('enable_session_timeout', models.BooleanField(default=True, help_text='Habilitar límite de tiempo de sesión')),
                ('show_timeout_warning', models.BooleanField(default=True, help_text='Mostrar advertencia antes de cerrar la sesión')),
                ('warning_time_minutes', models.PositiveIntegerField(default=5, help_text='Minutos antes del timeout para mostrar advertencia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Sesión',
                'verbose_name_plural': 'Configuraciones de Sesión',
            },
        ),
    ]
