# Generated by Django 5.2.3 on 2025-07-27 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptask', '0012_sessionconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='is_group_delivery',
            field=models.BooleanField(default=False, help_text='Si está marcado, esta entrega representa a todo el grupo'),
        ),
        migrations.AddField(
            model_name='task',
            name='is_group_task',
            field=models.BooleanField(default=False, help_text='Si está marcado, esta es una tarea grupal'),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del grupo (ej: Grupo A, Equipo 1)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='apptask.schoolclass')),
                ('students', models.ManyToManyField(limit_choices_to={'role': 'student'}, related_name='student_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'unique_together': {('name', 'school_class')},
            },
        ),
        migrations.AddField(
            model_name='delivery',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Grupo al que pertenece esta entrega (para entregas grupales)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='apptask.group'),
        ),
        migrations.AddField(
            model_name='task',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Grupo específico para esta tarea (opcional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='apptask.group'),
        ),
    ]
